global:
  registry: 635457411372.dkr.ecr.us-east-1.amazonaws.com
  env: dev
frontend:
  replicas: 1
  maxReplicas: 4
  tag: "develop-7f6c98cf"
auth:
  replicas: 1
  maxReplicas: 4
  tag: "develop-7f6c98cf"
book:
  replicas: 1
  maxReplicas: 4
  tag: "develop-7f6c98cf"
search:
  replicas: 1
  maxReplicas: 4
  tag: "develop-5586bd5d"
payment:
  replicas: 1
  maxReplicas: 4
  tag: "develop-5586bd5d"
notification:
  replicas: 1
  maxReplicas: 4
  tag: "develop-e04467bd"
postgres:
  host: dev-microservices-postgres.cg9mq6cuoriv.us-east-1.rds.amazonaws.com
  user: bookinguser
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
pdb:
  maxUnavailable: 1
