# environments/dev/values.yaml
# Image tags are automatically bumped by the CI pipeline (gitops-update job)

frontend:
  tag: latest
auth-service:
  tag: latest
notification-service:
  tag: develop-97e01d45
payment-service:
  tag: latest
search-service:
  tag: latest
booking-service:
  tag: latest
